### PR TITLE
feat: add support for Python 3.12

### LINKED ISSUE #900: Add support for Python 3.12
Python 3.12 was released in October 2023, time to support it.

https://www.python.org/downloads/release/python-3120/

### PR DESCRIPTION
**Pull request by jackwotherspoon**
Add that Python Connector officially supports [Python 3.12](https://www.python.org/downloads/release/python-3120/)

Closes #900

### CODE REVIEW

**Comment by jackwotherspoon** [comment]
Python 3.12 no longer comes with `setuptools` (i.e `pkg_resources`) as mentioned in https://docs.python.org/3/whatsnew/3.12.html

This causes issues with `pytds` driver that imports `pkg_resources`  in its [`__init__.py`](https://github.com/denisenkom/pytds/blob/master/src/pytds/__init__.py#L69)
```
.nox\system-3-12\Lib\site-packages\pytds\__init__.py:69: in <module>
    import pkg_resources  # type: ignore # fix later
E   ModuleNotFoundError: No module named 'pkg_resources'
```

Opened https://github.com/denisenkom/pytds/pull/157 PR as a potential fix.

**Comment by jackwotherspoon** [comment]
`python-tds` PR has been merged, should wait till release of `1.15.0` next month prior to merging this PR

**Review by enocom — APPROVED** [review]
Do we need to add a note about pytds? Probably not?

**Comment by jackwotherspoon** [comment]
> Do we need to add a note about pytds? Probably not?

@enocom No we will just wait till the new release of `pytds` driver and the version bump in this repo should then make these builds green.

**Pull request merged**
